---
abstract: 'build a Build.PL that uses Module::Build::Database'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::DZil: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ModuleBuildDatabase
no_index:
  directory:
    - corpus
requires:
  AnyEvent: 0
  AnyEvent::Open3::Simple: 0
  Dist::Zilla::App: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  File::Copy: 0
  File::chdir: 0
  Moose: 0
  Path::Class::Dir: 0
  perl: v5.10.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-ModuleBuildDatabase
  homepage: http://perl.wdlabs.com/dist/Dist-Zilla-Plugin-ModuleBuildDatabase/
version: 0.03_02
