---
abstract: 'build a Build.PL that uses Module::Build::Database'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::DZil: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ModuleBuildDatabase
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla::Plugin::ModuleBuild: 0
  Moose: 0
  perl: v5.10.0
version: 0.02
